services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: magadiflo
      POSTGRES_DB: db_hexagonal_architecture
    ports:
      - 5432:5432
    restart: unless-stopped